### ISSUE TITLE
Null array error when data table contains only one element  

### ISSUE THREAD

**Issue by OwenMeany57** [EvotecIT/PSWritePDF#10]
Since v.0.0.8, when using New-PDFTable, a null array error is thrown if the -DataTable array contains only one element:

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\PSWritePDF\0.0.8\PSWritePDF.psm1:343 char:9
+     if ($DataTable[0] -is [System.Collections.IDictionary]) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Using "New-PDFTable -DataTable $Data", the input array was: 
$Data = @(
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3' }
)

If at least one more element is added to this input array, a PDF will be generated as expected. This error did not occur prior to version 0.0.8.

**Comment by PrzemyslawKlys** [comment]
I have no clue why it wasn't working. I simply rebuilt PSWritePDF and it … works.

**Comment by PrzemyslawKlys** [comment]
Published new version. Give it a try please. Added tests for this case and it seems to work.

**Comment by OwenMeany57** [comment]
It appears to work now. Thank you!

**Comment by OwenMeany57** [comment]
This solved the null array issue, thank you. But it seems to have introduced a new issue with bolding text. 

 

The code: New-PDFText  -Text ‘Title1’, $value1 -Font HELVETICA -FontColor BLACK -FontBold $true, $false produces a PDF with the title bolded and the value not bolded, as expected.

 

However, the code: New-PDFText  -Text ‘Title1’, $value1, ‘Title2’, $value2 -Font HELVETICA -FontColor BLACK -FontBold $true, $false, $true, $false produces a PDF with no bolding at all.

 

It seems that once bold is toggled on and off, it prevents bold from working for that entire line. This feature worked fine in previous versions.

 

Do you want me to file a bug ticket?

 

Thanks!

**Comment by PrzemyslawKlys** [comment]
As always ;-) Best with reproduction code :-) It's weird that it happens when I have not touched original code. Maybe updates to iText library broke it.

**Comment by OwenMeany57** [comment]
I did a clean reinstall of the module and the problem persists.

 

I was able to create a workaround for the null array issue by adding a blank first element to the single-element arrays, which kept my script from breaking. I don’t think there’s a workaround for this one, though. I’ll keep v.0.0.8 running in production with my workaround in place.

**Comment by PrzemyslawKlys** [comment]
If you can send me sample code to reroduce it, ill fix it.

**Comment by OwenMeany57** [comment]
Here you go. Thank you!!

 

$path = "C:\Test\TestPDF.pdf"

$value1 = 'This bolding example works.'

$value2 = 'The second bolding example breaks them both.'

 

New-PDF -MarginLeft 20 -MarginRight 20 -MarginTop 20 -MarginBottom 20 {

    New-PDFPage -PageSize A4 {

        New-PDFText -Text 'The goal is to have the titles bolded and the values in normal font:'  -Font HELVETICA -FontColor BLACK 

        New-PDFText -Text 'Title: ', $value1  -Font HELVETICA -FontColor BLACK -FontBold $true, $false 

        New-PDFText -Text "But with more than one toggle, the bolding doesn't work at all:"  -Font HELVETICA -FontColor BLACK 

        New-PDFText -Text 'Title: ', $value1, '     Title2: ', $value2 -Font HELVETICA -FontColor BLACK -FontBold $true, $false, $true, $false 

        New-PDFText -Text "This worked in previous versions."  -Font HELVETICA -FontColor BLACK 

    }

} -FilePath $path -Show

**Comment by PrzemyslawKlys** [comment]
I've found the issue. It's coming from my function Remove-EmptyValue.

Never knew that empty string compared to boolean false will give $true
```
$false -eq ''
```

Updated module. Should work now. Sorry for that. 

Added a lot of tests for that: https://github.com/EvotecIT/PSSharedGoods/blob/master/Tests/Remove-EmptyValue.Tests.ps1

**Comment by OwenMeany57** [comment]
Yep, that seems to have fixed it. Thank you so much!

 

I like your little project. I look forward to additional enhancements.

 

Wayne Bender

11450 Mears Drive

Zionsville, IN 46077-9819
