### ISSUE TITLE
If Output File already exists powershell ISE is crashing and closing

### ISSUE THREAD

**Issue by Greyland99** [EvotecIT/PSWritePDF#14]
Hi,

regonized another failure. If the Output File already exists, than the whole ISE crashes.
Normally i add Unix timestamp to files to avoid this, but in the last example case i uploaded here #13 I recognized this beahavior.
Additional all other work was lost, so the normal behavior that a killed ISE resumes unsaved work didn't work.

Kind regards.

**Comment by PrzemyslawKlys** [comment]
I don't think it's related to the existing PDF. I've seen behavior where if PSWritePDF module crashes or not closes file after it's done (for example - during debug) it will stay open for the remaining time making that file unusable.
