### ISSUE TITLE
Update iText & BouncyCastle Crypto

### ISSUE THREAD

**Issue by user8446** [EvotecIT/PSWritePDF#17]
Hello,

I tested your module with the latest [iText v7.1.14](https://www.nuget.org/packages/itext7/) , [iText.hyph v7.1.14](https://www.nuget.org/packages/itext7.hyph/), and [BouncyCastle v1.8.10](https://www.nuget.org/packages/Portable.BouncyCastle/), and all works as expected. All have security/bugfixes/improvements. 
I hope this helps.
Thank you for the module!

**Comment by PrzemyslawKlys** [comment]
Care to make a PR?

**Comment by user8446** [comment]
Due to time, how about another donation?

**Comment by PrzemyslawKlys** [comment]
Up to you. Thank you :-)

I'll update it later on. Though you may have already done this or wanted an opportunity to try things :-)

**Comment by user8446** [comment]
Just sent, thank you!

**Comment by PrzemyslawKlys** [comment]
I will have to use BouncyCastle 1.8.9, not 10, as iText complains. Otherwise, I would need to recompile iText.

**Comment by user8446** [comment]
Ok FYI all I did was replace the all of the associated dll and then run my scripts and all worked. I now realize I forgot to try creating a PDF and this is only on a Windows machine.

**Comment by PrzemyslawKlys** [comment]
Ye, net works, PS 7.2 not so much. I'll have to check why it fails.

**Comment by PrzemyslawKlys** [comment]
Released new version.
