### ISSUE TITLE
License MIT ?

### ISSUE THREAD

**Issue by lazywinadmin** [EvotecIT/PSWritePDF#2]
Hey @PrzemyslawKlys ! Another great module! :) Thanks for that
Any plan to move the license to MIT ?

**Comment by PrzemyslawKlys** [comment]
Hi :-) 

As explain in https://evotec.xyz/merging-splitting-and-creating-pdf-files-with-powershell/

> PSWritePDF is based on NET iText 7 library, and the licensing of it is strictly related to requirements of that library – and that means it's licensed under AGPL. I would be more than happy to make PowerShell part MIT, but I am no licensing expert, and therefore, for now (or forever, it will stay licensed the same way iText 7 is licensed). 

This needs to be assessed by some licensing lawyers. As far as I am concerned the PowerShell code is MIT.
