### ISSUE TITLE
Split-PDF

### ISSUE THREAD

**Issue by lispeedyg** [EvotecIT/PSWritePDF#21]
Hi, Excellent tool.  I was wondering if it would be possible to:

1. Split all pdf's in a folder
2. Use the original pdf names in the output file appended with the page no, i.e., ABC-xxx.pdf (Where xxx is PDF page)

Thanks for the excellent tool!!

**Comment by PrzemyslawKlys** [comment]
Yes, it should be possible. 

Use Get-ChildItem on that folder, do the foreach, on each entry in loop split the PDF and provide the path where to split it, if necessary rename the output files to a required naming convention.
