### ISSUE TITLE
Merge-PDF - failed with error: "3": "PdfReader is not opened with owner password"

### ISSUE THREAD

**Issue by AlfredBSN** [EvotecIT/PSWritePDF#26]
is there a way to specify " reader.setUnethicalReading(true); "?

**Comment by PrzemyslawKlys** [comment]
Not at the moment, but we should consider this and few other things: https://kb.itextpdf.com/home/search?q=How%20to%20decrypt%20a%20PDF%20document%20with%20the%20owner%20password?&max=500&s=IT7KB to have

**Comment by PrzemyslawKlys** [comment]
Will be in next version
