### ISSUE TITLE
New-PDF without arguments crashes PowerShell 7.0.0-rc1

### ISSUE THREAD

**Issue by jantari** [EvotecIT/PSWritePDF#3]
Hi.

In PSWritePDF 0.0.5 - just installed from Gallery - running just `New-PDF` without any further parameters instantly crashes/closes PowerShell 7.0.0-rc1 when running inside the new Windows Terminal (v. 0.7.3451.0). When running from the ol' conhost terminal, it just prints the following:

```
WARNING: New-InternalPDF - Terminating error: Exception calling ".ctor" with "1" argument(s): "Empty path name is not legal. (Parameter 'path')"
```

but does not crash.

**Comment by PrzemyslawKlys** [comment]
It's not supposed to be used like that. I can, of course, fix this, but you need to give a path to where to save the file?

**Comment by PrzemyslawKlys** [comment]
```powershell
Import-Module .\PSWritePDF.psd1 -Force

New-PDF  -MarginLeft 520 { #520 -MarginRight 20 -MarginTop 20 -MarginBottom 20 -PageSize B4 -Rotate {
    New-PDFText -Text 'Test ', 'Me', 'Oooh' -FontColor BLUE, YELLOW, RED
    New-PDFList {
        New-PDFListItem -Text 'Test'
        New-PDFListItem -Text '2nd'
    }
} -FilePath "$PSScriptRoot\Example01_MoreOptions.pdf" -Show
```

Is the proper way.

**Comment by jantari** [comment]
Yes of course, but the expected behavior of a PowerShell cmdlet would be to have the `-FilePath` parameter tagged as `Mandatory = $true` so that PowerShell asks for it instead of crashing or throwing iText warnings.

**Comment by PrzemyslawKlys** [comment]
yes sure ;-) care to provide PR? :)

**Comment by jantari** [comment]
Not this week unfortunately, I am using the module right now to help me get 126 pages of something done in time which is uuuuuh gonna take most of my time ^^

I'd be happy to look into it later though
