### ISSUE TITLE
Is there a way to add a page break?

### ISSUE THREAD

**Issue by c3rberus** [EvotecIT/PSWritePDF#30]
Using PSWritePDF to output some data from PowerShell script, is there a way to add a page break?

**Comment by PrzemyslawKlys** [comment]
Can't you use it via PDFPage?

https://github.com/EvotecIT/PSWritePDF/blob/master/Example/Example01.HelloWorld/Example01_WithSections.ps1

There are also other examples in Examples folder?

**Comment by c3rberus** [comment]
Perfect, thank you. I didn't realize you can call New-PDFPage more than once. Thanks :)
