### ISSUE TITLE
Number PDF Pages or include a footer note

### ISSUE THREAD

**Issue by yaroslavpaz** [EvotecIT/PSWritePDF#33]
Hi there!
It would be a great feature if we could  number PDF Pages or include a footer note when creating a new PDF
Merry Christmas!

**Comment by yaroslavpaz** [comment]
Hi PremyslawKlys
Is this a feature because it is nowhere to find inside the powershell module, can you show me please?

**Comment by PrzemyslawKlys** [comment]
You opened two issues with same question. I closed one of them.
