### ISSUE TITLE
Register-PDFFont failed to add kaiu.ttf

### ISSUE THREAD

**Issue by Matt79080701** [EvotecIT/PSWritePDF#37]
I used New version 0.0.18 add kaiu.ttf.
but I’not working,but used to old version 0.0.17
add completed and can output pdf.

maybe is encoding something wrong.
my windows language is chinese-traditional 

I want to used 0.0.18 New-PDFImage function.
can I just add this Function to 0.0.17?

**Comment by PrzemyslawKlys** [comment]
What is the error message? Adding function between versions is possible but you would need to add relevant code (not just the missing function).

**Comment by Matt79080701** [comment]
run 0.0.18  version to chinese-traditional windows language
If just add image will show  New-InternalPDF - Terminating Error "1" ..".ctor"..message
![image](https://user-images.githubusercontent.com/103615155/163411841-8de97ce8-a5e9-441b-bd19-019ac186b4f2.png)

If Register-PDFFont will show Font Registration failed. Error: "Create Font" ".ctor" .."3".. message
![image](https://user-images.githubusercontent.com/103615155/163412210-2e8fd8ec-b3b7-412e-8857-6224f805d4d6.png)

Can you help me just add the function "New-PDFImage" and where to find what's missing relevant code.
How to add to 0.0.17. Thank you

**Comment by PrzemyslawKlys** [comment]
You're using it wrong. 

```powershell
New-PDF -FilePath "$PSScriptRoot\Example01_Simple3-2.pdf" -PDFContent {
    Register-PDFFont -FontName 'Verdana' -FontPath 'C:\Windows\fonts\verdana.ttf' -Encoding IDENTITY_H -Cached -Default
    New-PDFText -Text 'Hello ', 'Привет !'
} -Show
```

The Register-PDFFont has to be inside the New-PDF.

**Comment by Matt79080701** [comment]
I did as you said.
But Register-PDFFont Error to CreateFont
![image](https://user-images.githubusercontent.com/103615155/163419648-aad599fc-a810-4775-b3c8-2914c0213f99.png)

**Comment by Matt79080701** [comment]
same command line used to 0.0.17 can out put pdf file.  and does not show errors
![image](https://user-images.githubusercontent.com/103615155/163421451-13cfc16e-15d7-46e7-aab3-dc4e3e64445c.png)

**Comment by PrzemyslawKlys** [comment]
Please send the font so I can check it

**Comment by Matt79080701** [comment]
This is Fonts info. But I dont know how to download.
https://docs.microsoft.com/en-us/typography/font-list/dfkai-sb

**Comment by Matt79080701** [comment]
My system environment 
![image](https://user-images.githubusercontent.com/103615155/163425659-3752321a-4cc9-488b-9542-83e277d59af3.png)

**Comment by Matt79080701** [comment]
Hi,there

I debugged myself for a while but I haven't found out the reason, is there any news that I can provide, God bless you

**Comment by PrzemyslawKlys** [comment]
It's my fault. Something must have changed between versions. I think I fixed it. I will release new version

**Comment by Matt79080701** [comment]
Hi,Matt again

Register-PDFFont is fixed in new version.
But can not output pdf file with 0.0.18 & 0.0.19

![image](https://user-images.githubusercontent.com/103615155/166462621-a1a29869-28c6-47ce-a241-a2a29aa60f71.png)

**Comment by PrzemyslawKlys** [comment]
Open a new issue, and please make sure to translate the error message because with those errors - I can't read them.
