### ISSUE TITLE
Get-PDFNamedPageSize has typo on line 66 causing Error: A null key is not allowed in a hash literal.

### ISSUE THREAD

**Issue by BrooksV** [EvotecIT/PSWritePDF#50]
Line 66
`return [PSCustomObject] @{ PageSize = 'Unknown'; $Rotated = $null }
`
$Rotated needs to be Rotated as it's not a variable but a property name
`return [PSCustomObject] @{ PageSize = 'Unknown'; Rotated = $null }`

**Comment by PrzemyslawKlys** [comment]
Care to create PR?
