### ISSUE TITLE
Using variables with custom text in pdf

### ISSUE THREAD

**Issue by oliwex** [EvotecIT/PSWritePDF#6]
How to use variables to add custom text from user? Examples dont have info about it :(

**Comment by PrzemyslawKlys** [comment]
Define variables at the top or within script and use them?

The blog post shows some examples: https://evotec.xyz/merging-splitting-and-creating-pdf-files-with-powershell/ 

Especially those with Tables, but any text can be replaced with variable? Or am I missing something?

**Comment by PrzemyslawKlys** [comment]
Closing as stale.
