### ISSUE TITLE
Incorrect display of hashtables

### ISSUE THREAD

**Issue by Greyland99** [EvotecIT/PSWritePDF#7]
Hi,
I have been working with 'New-PDFTable' and noticed a very unusual behavior. While the examples worked perfectly, my own code did not work. If I manually inserted something into $DataTable2, it worked again. If the variable was adjusted, not anymore.

As far as I could see the problem is in the function 'New-InteralPDFTable' and the line
`
'[Array] $TemporaryTable = foreach ($_ in $DataTable2) {'`

the function must be changed to
`'[Array] $TemporaryTable = foreach ($_ in $DataTable) {'`

So far it seems to be working. Can you verify the error?

**Comment by PrzemyslawKlys** [comment]
Ye, sure - it seems like a mistake. Will fix.

**Comment by PrzemyslawKlys** [comment]
Silly little mistake - it was working because an example had DataTable2 as a name. Published new, signed version. Please test and come back if something doesn't work.

**Comment by Greyland99** [comment]
I thought that this was the reason. Will test it tomorrow. 




On Tue, Jul 21, 2020 at 7:32 PM +0200, "Przemysław Kłys" <notifications@github.com> wrote:















Silly little mistake - it was working because an example had DataTable2 as a name. Published new, signed version. Please test and come back if something doesn't work.
